config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # main page will already show the lists index page!
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # each bookmark belongs to a movie
  belongs_to :movie
  # and a list
  belongs_to :list

  validates :comment, length: { minimum: 6, maximum: 500 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "has already been added to this list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  # destroy bookmarks if a list is deleted
  has_many :bookmarks, dependent: :destroy
  # "Hey Rails, from a List, I want access to all the Movies through the Bookmarks table"
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # one movie can appear in many bookmarks
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks

  # validates the presence of title and overview, and prevents duplicate titles
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # set_bookmark: runs before destroy, so we can find the bookmark we're trying to delete
  before_action :set_bookmark, only: :destroy
  # set_list: runs before new and create, to load the correct list for the form or the newly created bookmark
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "Movie added to the list!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: "Bookmark was successfully deleted."
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: "List created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie,
      collection: Movie.all.order(:title),
      prompt: "Select a movie",
      input_html: { data: { controller: "tom-select" } } %>

  <%= f.input :comment, placeholder: "Enter a comment about the movie" %>

  <%= f.submit "Add movie", class: "btn btn-flat" %>
  <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
<% end %>

app/views/bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>

        <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>

        <%= link_to "Back to list", list_path(@list), class: "btn btn-secondary mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- External Styles -->
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <!-- Required for Bootstrap modal and nav toggler -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYhE6fVbS5O+WEMfFZ1FAdhGwL5YkN0FSJ5uXG5J"
      crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-4">
    <h3 class="mb-0 display-6">My Lists <small class="text-muted">(<%= pluralize(@lists.count, "list") %>)</small></h3>
    <%= link_to "Create New List", new_list_path, class: "btn btn-flat btn-primary" %>
  </div>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 col-sm-6 col-md-4 mb-4">
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="card-category shadow-sm rounded" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? url_for(list.photo) : asset_path('banner.jpg') %>)">

            <div class="text-white fw-bold d-flex justify-content-between align-items-center px-3 py-2" style="height: 100%;">
              <span><%= list.name %></span>
              <span class="badge bg-light text-dark"><%= pluralize(list.bookmarks.count, "movie") %></span>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-4 shadow">
        <h3 class="mb-4">Create a New List</h3>

        <%= simple_form_for @list, html: { multipart: true, data: { turbo: false } } do |f| %>
          <%= f.input :name, placeholder: "Drama" %>
          <%= f.input :photo, as: :file, label: "Upload a banner image" %>
          <%= f.button :submit, "Save", class: "btn btn-success" %>
        <% end %>

        <%= link_to "⬅ Go Back to All Lists", root_path, class: "btn btn-outline-dark mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative mb-4">
  <div class="card-category card-large"
  style="background-image: linear-gradient(
  rgba(0,0,0,0.3),
  rgba(0,0,0,0.3)),
  url(<%= @list.photo.attached? ? url_for(@list.photo) : asset_path('banner.jpg')%>)">
   <h1 class= "text-white"><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, "movie") %></span>
</div>

<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <%= link_to "⬅ Back to All Lists", root_path, class: "btn btn-outline-dark" %>

    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        ➕ Add a movie
      </button>
      <%= link_to "🗑 Delete this list", list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>

  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 d-flex flex-column h-100 justify-content-between">
            <div>
              <strong><%= movie.title %> <span class="text-muted">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
              <p class="text-muted small mt-2"><%= truncate(movie.overview, length: 200) %></p>
              <p class="text-muted"><i class="fas fa-quote-left me-2"></i><%= bookmark.comment %></p>
            </div>
            <div class="text-end">
              <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from this list?" }, class: "btn btn-link text-danger p-0" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <hr class="my-5">

  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>

      <% @list.reviews.each do |review| %>
        <div class="mb-3">
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small class="text-muted"><em><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>

    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3 shadow-sm">
        <h5 class="mb-3">Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: 1..5, required: true, label: false, input_html: { data: { controller: "star-rating" } } %>
          <%= f.submit "Submit Review", class: "btn btn-flat mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "bookmarks/modal", list: @list, bookmark: @bookmark %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "popcorn.png", alt: "alttext", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "My lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>